spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pearprogram}
    username: ${SPRING_DATASOURCE_USERNAME:pear}
    password: ${SPRING_DATASOURCE_PASSWORD:pear}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
management:
  health:
    redis:
      enabled: ${SPRING_REDIS_HEALTH_ENABLED:false}
